<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\StockManager.Core\StockManager.Core.csproj" />
    <ProjectReference Include="..\StockManager.Data\StockManager.Data.csproj" />
    <ProjectReference Include="..\StockManager.Print\StockManager.Print.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.46.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
